branch-protection:
  orgs:
    validatedpatterns:
      repos:
        docs:
          unmanaged: true

tide:
  queries:
  - labels:
    - lgtm
    - approve
    missingLabels:
    - backports/unvalidated-commits
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - jira/invalid-bug
    - needs-rebase
    repos:
    - validatedpatterns/docs
